FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY tsconfig*.json .

COPY prisma ./prisma

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 4000

CMD [ "node","dist/index.js" ]